services:
  navigation-app:
    build: .
    container_name: kk-navigation
    user: root
    ports:
      - "4567:4567"
    volumes:
      # 持久化数据库文件
      - ./data:/app/data
      # 可选：挂载配置文件（如果需要外部配置）
      - ./config:/app/config:ro
    environment:
      # 应用环境
      - RACK_ENV=production
      # 会话密钥（生产环境请使用更安全的密钥）
      - SESSION_SECRET=your_very_secure_session_secret_key_here_at_least_32_bytes_long
      # 数据库路径
      - DATABASE_PATH=/app/data/navigation.db
      # 时区设置
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4567/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navigation.rule=Host(`navigation.yourdomain.com`)"
      - "traefik.http.routers.navigation.tls=true"
      - "traefik.http.routers.navigation.tls.certresolver=letsencrypt"
      - "traefik.http.services.navigation.loadbalancer.server.port=4567"
    networks:
      - navigation-network

  # 可选：添加反向代理（Nginx）
  nginx:
    image: nginx:alpine
    container_name: kk-navigation-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - navigation-app
    restart: unless-stopped
    networks:
      - navigation-network

networks:
  navigation-network:
    driver: bridge

volumes:
  navigation-data:
    driver: local
