services:
  navigation-app:
    build: .
    container_name: kk-navigation
    ports:
      - "4567:4567"
    volumes:
      # 持久化数据库文件
      - ./data:/app/data
    environment:
      # 应用环境
      - RACK_ENV=production
      # 会话密钥（请在生产环境中更改）
      - SESSION_SECRET=your_very_secure_session_secret_key_here_at_least_32_bytes_long
      # 数据库路径
      - DATABASE_PATH=/app/data/navigation.db
      # 时区设置
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4567/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s